### ISSUE TITLE
Некорректный результат

### ISSUE THREAD

**Issue by vkats-spbu** [danil-korovin/LabWork1#1]
см. результатт прогона 
[result.zip](https://github.com/user-attachments/files/18188560/result.zip)

**Comment by MarryAnt** [comment]
![Screenshot from 2024-12-20 13-26-03](https://github.com/user-attachments/assets/85b51788-7b68-4e3c-824a-4b916eaf8d44)

**Comment by danil-korovin** [comment]
Исправил ошибки

**Comment by vkats-spbu** [comment]
Перерасход памяти. Оценка C. Все операции можно было выполнить без копирования массива пикселей.
